<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="7" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="1753" started-at="2020-04-08T09:55:55Z" finished-at="2020-04-08T09:55:56Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="1753" started-at="2020-04-08T09:55:55Z" finished-at="2020-04-08T09:55:56Z">
      <class name="TestItems">
        <test-method status="PASS" signature="TestOperationsItems()[pri:0, instance:TestItems@4c550889]" name="TestOperationsItems" duration-ms="342" started-at="2020-04-08T12:55:55Z" finished-at="2020-04-08T12:55:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestOperationsItems -->
        <test-method status="PASS" signature="addBagInStack()[pri:0, instance:TestItems@4c550889]" name="addBagInStack" duration-ms="21" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addBagInStack -->
        <test-method status="PASS" signature="addContainerToContainer()[pri:0, instance:TestItems@4c550889]" name="addContainerToContainer" duration-ms="3" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addContainerToContainer -->
        <test-method status="PASS" signature="mistakesStoreOperationItems()[pri:0, instance:TestItems@4c550889]" name="mistakesStoreOperationItems" duration-ms="6" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <exception class="ItemAlreadyPlacedException">
            <message>
              <![CDATA[Этот предмет уже где-то лежит]]>
            </message>
            <full-stacktrace>
              <![CDATA[ItemAlreadyPlacedException: Этот предмет уже где-то лежит
	at Bag.addItem(Bag.java:27)
	at Box.addItemContainer(Box.java:12)
	at TestItems.mistakesStoreOperationItems(TestItems.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- ItemAlreadyPlacedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mistakesStoreOperationItems -->
        <test-method status="PASS" signature="mistakesWeightOperationItems()[pri:0, instance:TestItems@4c550889]" name="mistakesWeightOperationItems" duration-ms="17" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <exception class="ItemStoreException">
            <message>
              <![CDATA[Нельзя положить больше 5.0 кг]]>
            </message>
            <full-stacktrace>
              <![CDATA[ItemStoreException: Нельзя положить больше 5.0 кг
	at Bag.addItem(Bag.java:24)
	at TestItems.mistakesWeightOperationItems(TestItems.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- ItemStoreException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mistakesWeightOperationItems -->
        <test-method status="PASS" signature="testCreateContainerItems()[pri:0, instance:TestItems@4c550889]" name="testCreateContainerItems" duration-ms="3" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateContainerItems -->
        <test-method status="PASS" signature="testCreateItems()[pri:0, instance:TestItems@4c550889]" name="testCreateItems" duration-ms="4" started-at="2020-04-08T12:55:56Z" finished-at="2020-04-08T12:55:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateItems -->
      </class> <!-- TestItems -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
